apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-import
  namespace: keycloak
type: Opaque
stringData:
  mlops-realm.json: |
    {
      "realm": "mlops",
      "enabled": true,
      "displayName": "MLOps Technical Challenge",
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "verifyEmail": false,
      "clients": [
        {
          "clientId": "${OAUTH2_PROXY_CLIENT_ID}",
          "name": "Loadtester",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "secret": "${OAUTH2_PROXY_CLIENT_SECRET}",
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true,
          "redirectUris": [
            "http://host.k3d.internal:8080/oauth2/callback"
          ],
          "webOrigins": [
            "http://host.k3d.internal:8080"
          ],
          "protocolMappers": [
            {
              "name": "loadtester-audience",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "${OAUTH2_PROXY_CLIENT_ID}",
                "id.token.claim": "true",
                "access.token.claim": "true"
              }
            },
            {
              "name": "service-account-email",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-hardcoded-claim-mapper",
              "consentRequired": false,
              "config": {
                "claim.name": "email",
                "claim.value": "loadtester-service@example.com",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "users": [
        {
          "username": "${DEMO_USER_USERNAME}",
          "enabled": true,
          "email": "${DEMO_USER_EMAIL}",
          "emailVerified": true,
          "firstName": "Demo",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "${DEMO_USER_PASSWORD}",
              "temporary": false
            }
          ]
        }
      ]
    }